FROM docker.io/library/ubuntu:24.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        software-properties-common

RUN curl --fail --show-error --silent --location \
        https://propheseeai.jfrog.io/artifactory/api/security/keypair/prophesee-gpg/public \
        --output /etc/apt/trusted.gpg.d/prophesee.asc \
    && add-apt-repository --yes \
        'https://propheseeai.jfrog.io/artifactory/openeb-debian/' \
    && apt-get update

CMD ["bash", "-lc", "apt-cache policy metavision-openeb && apt-cache madison metavision-openeb"]
